name: Release Pack
  # You may pin to the exact commit or the version.
  # uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
    
on:
  push:
     branches: [ main ]
     
jobs:
 retrievingVersion:
  runs-on: ubuntu-latest
  outputs:
      version: ${{ steps.versionstep.outputs.version }}
  steps:
    - uses: actions/checkout@v3
    - id: set_var
      run: |
          content=`cat ./main/jbg.config.jet`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"
    - run: |
          VERSION=${{fromJson(steps.set_var.outputs.packageJson).buildVersion}}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      name: Retrieve Release Version         
 upload:
    runs-on: ubuntu-latest
    needs: 
      - retrievingVersion
    steps: 
      - uses: actions/checkout@v3
      - run: mkdir -p outputs
      - name: Zipping windows release
        working-directory: main
        run: |
          zip -r ../outputs/JPP8.zip *
      - name: Upload release onto Github
        uses: ncipollo/release-action@v1
        with:
         artifacts: '../outputs/JPP8.zip'
         token: ${{ secrets.GITHUB_TOKEN }}
         tag: ${{ needs.retrievingVersion.outputs.version }}
         prerelease: false
         allowUpdates: true
